---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-dbb-script
spec:
  params:
    - name: zosSshKey
      description: The z/OS SSH private key
  steps:
    - name: run-dbb-script
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: ZOS_SSH_KEY
          value: $(params.zosSshKey)
      script: |
        #!/bin/bash
        echo "Running dbb build task now..."
        echo $PWD
        echo $ls
        cat /etc/os-release
        whoami
        apt-get update
        apt-get install iputils-ping
        sudo apt-get install inetutils-traceroute
        traceroute 9.30.160.8
        ping -c 4 9.30.160.8
        echo $ZOS_SSH_KEY > id_rsa
        chmod 700 id_rsa
        ssh -vvv -i id_rsa -o "StrictHostKeyChecking=no" ibmuser@9.30.160.86 -p 31652 "/u/ibmuser/myscript.sh"
