---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-dbb-script
spec:
  params:
    - name: zosSshKey
      description: The z/OS SSH private key
  steps:
    - name: run-dbb-script
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: ZOS_SSH_KEY
          value: $(params.zosSshKey)
      script: |
        #!/bin/bash
        echo "Running dbb build task now..."
        echo $PWD
        echo $ls
        whoami
        echo $ZOS_SSH_KEY | base64 -w 0 --decode > id_rsa
        chmod 700 $ZOS_SSH_KEY
        ssh -i id_rsa -o "StrictHostKeyChecking=no" ibmuser@wazidev-demo-inf.fyre.ibm.com -p 31652 "/u/ibmuser/myscript.sh"
