---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-dbb-script
spec:
  steps:
    - name: run-dbb-script
      image: ibmcom/pipeline-base-image:2.6
      script: |
        #!/bin/bash
        echo "Running dbb build task now..."
        echo $PWD
        whoami
