---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-dbb-script
spec:
  params:
    - name: zosSshKey
      description: The z/OS SSH private key
  steps:
    - name: run-dbb-script
      image: ibmcom/pipeline-base-image:2.6
      env:
        - name: ZOS_SSH_KEY
          value: $(params.zosSshKey)
      script: |
        #!/bin/bash
        echo "Running dbb build task now..."
        echo $PWD
        echo $ls
        traceroute wazidev-demo-inf.fyre.ibm.com
        ping -c 2 wazidev-demo-inf.fyre.ibm.com
        # echo $ZOS_SSH_KEY | base64 -w 0 --decode > id_rsa
        echo "Will try to ssh into wazidev-demo-inf.fyre.ibm.com"
        chmod 700 $ZOS_SSH_KEY
        ssh -i $ZOS_SSH_KEY -o "StrictHostKeyChecking=no" ibmuser@9.30.160.86 -p 31652 "/u/ibmuser/myscript.sh"
        echo "ssh without they key"
        ssh ibmuser@9.30.160.86 -p 31652 "/u/ibmuser/myscript.sh"
        whoami
